base: IN19B
region: Region
consolidated: ConsolidatedSites
corporate: CorporateSummary
balance: StatementBalance
part: Part
opCos:
    - region: Alberta
      siteIds: 181,257,823
      siteNames: 181-Calgary,257-Edmonton,823-Calgary RDC
    - region: Atlantic
      siteIds: 262,264,265,268
      siteNames: 262-Moncton,264-St.John's,265-Halifax,268-Nasys
    - region: British_Columbia
      siteIds: 044,139,162
      siteNames: 044-Vancouver,139-Victoria,162-Kelowna
    - region: Corporate
      siteIds: 447,573,574,575,385,386,387
      siteNames: 447-SMS,573-SyscoCanada_FinancialServices,574-2234842_AlbertaULC,575-2234829_AlbertaULC,385-Holdings_Ltd,386-Holdings_of_BC,387-Holdings_of_Kelowna
    - region: Freshpoint
      siteIds: 127,127,127,127,300,302
      siteNames: 127-Freshpoint_Allied,127-Freshpoint_Nanaimo,127-Freshpoint_Vancouver,127-Freshpoint_Vanport,300-Freshpoint_VANFreshCut,302-Freshpoint_TORFreshCut
    - region: GWW
      siteIds: 220
      siteNames: 220-GWW
    - region: Ontario_North
      siteIds: 077,421,442
      siteNames: 077-Peterborough,421-Cash_and_Carry,442-Ottawa
    - region: Ontario_South
      siteIds: 180,256,273,338,838
      siteNames: 180-Toronto,256-Milton,273-Kingston,338-Southwestern_Ontario,838-SSWO RDC
    - region: Prairies
      siteIds: 258,259,336
      siteNames: 258-regina,259-Winnipeg,336-ThunderBay
    - region: Quebec
      siteIds: 331,417
      siteNames: 331-GrandMontreal,417-Mitshim
    - region: Speciality
      siteIds: 157,299,307,323,LaPointe
      siteNames: 157-SFM_Toronto,299-SFM_Vancouver,307-FinsSeafood,323-EnGrosPierre,LaPointe-CLOSED