rules:
  networkRules:
  -
    size: 10
    prefix: '255'
    regex:  '^([ ... some regex])\S$'
    -
      size: 11
      prefix: '180'
      regex: '^([ ... a cool regex ...])\S$'
    -
      size: 10
      prefix: '128'
      regex:  '^([ ... another regex...])\S$'